spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/menu_manager?createDatabaseIfNotExist=true
    username:
    password:
  liquibase:
    enabled: true
    change-log: /db/db.changelog-master.xml